source "https://rubygems.org"
gem "jekyll", github: "jekyll/jekyll"
gem "liquid-c"
gem "jekyll-commonmark"
gem "jekyll-include-cache"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-include-cache"
